### ISSUE TITLE
是否考虑支持Windows？

### ISSUE THREAD

**Issue by wwjCMP** [daodao97/chatmcp#5]
是否考虑支持Windows？

**Comment by daodao97** [comment]
要支持, 手头没有 win 设备, 无法打包, 我想想办法, 如果有哪位朋友有 win 设备 刚好会 flutter 可以帮忙打包一下

**Comment by InitialXKO** [comment]
在windows上打出来了包，但调用mcp的能力好像总是不会触发
![image](https://github.com/user-attachments/assets/3b8256a2-68a7-487a-9d2f-dea053e2a34a)
![image](https://github.com/user-attachments/assets/67b54ad9-4daa-412e-a33b-8aa2ca0b9c75)

**Comment by adhikasp** [comment]
Hi, I have a PR https://github.com/daodao97/chatmcp/pull/7 to add Windows build directly

It also fix Python-based MCP calls in windows, might also resolve your issue @InitialXKO
